### ISSUE TITLE
List of suggested Words

### ISSUE THREAD

**Issue by abhishakvarshneynykaa** [hellohaptik/spello#14]
Is there any method or config available where I can get list of suggested corrections rather than corrected words?
e.g. plai >> [play, plea, pola, pal] rather than plai >> play.

Is there any method or config available where I can get list of suggested corrections rather than corrected words?
e.g. plai >> [play, plea, pola, pal] rather than plai >> play.
P.S. Plz need a help. I am tagging you as I need a quick response in this threat.
+ @chiragjn @amansrivastava17

**Comment by chiragjn** [comment]
you can use the `_correct_word` method to get suggestions
```
model_path  = '/home/ubuntu/model.pkl'
sp = SpellCorrectionModel(language='en')
sp.load(model_path)
sp._correct_word('plai')
```

I'll mark this as an enhancement request, we can definitely refactor the interface and make this a public method with a proper name
