### ISSUE TITLE
When the model applies the correction?

### ISSUE THREAD

**Issue by Omarnabk** [hellohaptik/spello#16]
When the model tries to correct a word, does it consider the grammatical and semantical meaning of the sentence after correction? 
In other words, when the model decides to correct a word? only if it is not in its dictionary? or when the meaning is not correct?

**Comment by chiragjn** [comment]
Spello at the moment only attempts to correct a word if it is not in its vocabulary/dictionary. It does not consider the semantic meaning of the text
See: https://github.com/hellohaptik/spello#future-scope--limitations

This was a deliberate design decision to keep the overall algorithm generic and simple as semantic reasoning is quite challenging and varies from domain to domain
