### ISSUE TITLE
How would you apply spello to a pandas Column?

### ISSUE THREAD

**Issue by gsalfourn** [hellohaptik/spello#18]
I'm fairly new to python and just want to know how you would apply spello to text in a pandas dataframe column.

**Comment by chiragjn** [comment]
you can wrap it in function

```python
from spello.model import SpellCorrectionModel
sp = SpellCorrectionModel(language='en')
sp.load('/path/to/file/en.pkl')

def spell_correct(text):
    return sp.spell_correct(text)['spell_corrected_text']

df = ...
df['corrected_text'] = df['text'].apply(spell_correct)
```

I am closing this because in #19 it seems like you have managed to figure this out. Feel free to re-open with your specific example if you need any more help :)
