### ISSUE TITLE
Passing verbose to symspell function

### ISSUE THREAD

**Issue by aakashgaur01** [hellohaptik/spello#21]
By default, verbose=1 for SymSpell during initiation and there is no way to change it to 2 during the "spell_correct" function call or during creation of SpellCorrectionModel object.
Because of this, only the suggestion with smallest edit distance comes up and thus, Contextual Model doesnt work as expected.

**Comment by chiragjn** [comment]
Thanks for reporting this, you are correct, the verbose=1 forces early exit and there is no argument to change it directly. I am noting this as an enhancement. We'll expose this as an argument in the config already being passed. For now, I can only suggest a workaround

```python
from spello.model import SpellCorrectionModel  
sp = SpellCorrectionModel(language='en')  
sp.symspell_model.verbose = 2
```
